add validator.py
idangrosbard/neurosynth_autofeed pull request #20
Opened 2023-07-02 09:52 UTC by YuvNavon

@idangrosbard

2023-07-02 10:01 UTC, idangrosbard commented
1. Add `self` parameter to all function definitions
2. Add python typing for all function inputs and outputs
3. Add pytests for good and bad input cases. Check that each validator function works well

2023-07-02 10:03 UTC, idangrosbard requested changes
Add python typing
Add `self` parameter to all functions
Add pytests for all functions

2023-07-02 13:12 UTC, ORachelS requested changes

2023-07-02 13:12 UTC, ORachelS commented on validator.py
> +def test_test_coordinates(validator):
might be redundant, we already checked each one individually

2023-07-02 13:12 UTC, ORachelS commented on validator.py
> +def test_check_coordinates_is_int(validator):
maybe add a message that the tests pass or failed (the test for the validations)

2023-07-02 13:50 UTC, ORachelS approved these changes
looks great

2023-07-02 13:50 UTC, ORachelS approved these changes

2023-07-02 14:09 UTC, idangrosbard requested changes
Change `List[List[int]]` to `np.array` (numpy)

2023-07-03 08:37 UTC, idangrosbard approved these changes
Looks great :) 10 / 10

2023-07-03 08:38 UTC, merged